package model;
// Generated 25-mar-2016 10:30:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set medics = new HashSet(0);

    public Category() {
    }

    @Override
    public String toString() {
        return id.toString();
    }

    public Category(String name, Set medics) {
       this.name = name;
       this.medics = medics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMedics() {
        return this.medics;
    }
    
    public void setMedics(Set medics) {
        this.medics = medics;
    }




}


