package model;
// Generated 25-mar-2016 10:30:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pacient generated by hbm2java
 */
public class Pacient  implements java.io.Serializable {


     private Integer id;
     private String no;
     private String name;
     private String lastname;
     private String gender;
     private Date dayOfBirth;
     private String email;
     private String address;
     private String phone;
     private String image;
     private String sick;
     private String medicaments;
     private String alergy;
     private boolean isFavorite;
     private boolean isActive;
     private Date createdAt;
     private Set reservations = new HashSet(0);

    @Override
    public String toString() {
        return id + " - "+ name + " " + lastname;
    }

    public Pacient() {
    }

	
    public Pacient(boolean isFavorite, boolean isActive) {
        this.isFavorite = isFavorite;
        this.isActive = isActive;
    }

    public Pacient(Integer id) {
        this.id = id;
    }

    public Pacient(String no, String name, String lastname, String gender, Date dayOfBirth, String email, String address, String phone, String image, String sick, String medicaments, String alergy, boolean isFavorite, boolean isActive, Date createdAt, Set reservations) {
       this.no = no;
       this.name = name;
       this.lastname = lastname;
       this.gender = gender;
       this.dayOfBirth = dayOfBirth;
       this.email = email;
       this.address = address;
       this.phone = phone;
       this.image = image;
       this.sick = sick;
       this.medicaments = medicaments;
       this.alergy = alergy;
       this.isFavorite = isFavorite;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDayOfBirth() {
        return this.dayOfBirth;
    }
    
    public void setDayOfBirth(Date dayOfBirth) {
        this.dayOfBirth = dayOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getSick() {
        return this.sick;
    }
    
    public void setSick(String sick) {
        this.sick = sick;
    }
    public String getMedicaments() {
        return this.medicaments;
    }
    
    public void setMedicaments(String medicaments) {
        this.medicaments = medicaments;
    }
    public String getAlergy() {
        return this.alergy;
    }
    
    public void setAlergy(String alergy) {
        this.alergy = alergy;
    }
    public boolean isIsFavorite() {
        return this.isFavorite;
    }
    
    public void setIsFavorite(boolean isFavorite) {
        this.isFavorite = isFavorite;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


