package model;
// Generated 25-mar-2016 10:30:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set reservations = new HashSet(0);

    public Status() {
    }

    public Status(Integer id) {
        this.id = id;
    }

    public Status(String name, Set reservations) {
       this.name = name;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


