package model;
// Generated 25-mar-2016 10:30:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String name;
     private String lastname;
     private String email;
     private String password;
     private boolean isActive;
     private boolean isAdmin;
     private Date createdAt;
     private Set reservations = new HashSet(0);

    public User() {
    }

	
    public User(boolean isActive, boolean isAdmin) {
        this.isActive = isActive;
        this.isAdmin = isAdmin;
    }
    public User(String username, String name, String lastname, String email, String password, boolean isActive, boolean isAdmin, Date createdAt, Set reservations) {
       this.username = username;
       this.name = name;
       this.lastname = lastname;
       this.email = email;
       this.password = password;
       this.isActive = isActive;
       this.isAdmin = isAdmin;
       this.createdAt = createdAt;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


